### ISSUE TITLE
Can you undo the changes made in an earlier commit?

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/git-course#10]
Say you change all your \alpha's to \beta's in commit abcd77, do some more commits, and then decide that you want the \beta's back to \alpha's. Can you somehow easily just undo the changes you did in commit abcd77? 

Would be good (for more complex examples), though maybe fiddly. Just wondering, as someone might ask. And it may give motivation for doing branches.

**Comment by cgrandin** [comment]
Yes, it's really easy:

git revert HASH

where HASH is the SHA1 hash for the commit you want to undo (e.g. abcd77). This example illustrates the importance of making lots of commits, each with only small changes. You can only revert the whole commit, not parts. So, if you decide to change all \alpha's to \beta's, do that and only that in one commit so you can undo later if necessary.

I'll put a slide in about undoing things..

**Comment by andrew-edwards** [comment]
Did not know that - awesome. We could even include that in an exercise.
I also didn't remember that that abcd77 is called a hash! Kind of good for people to know the proper names for everything, but also not essential for actually using it.

**Comment by andrew-edwards** [comment]
Is that what you used towards the end of hake in 2016? I remember you capitalised a bunch of things in the bibliography but then I said not to because they weren't in the original references.

**Comment by cgrandin** [comment]
I believe so. Its a powerful tool if you have planned your commits properly!
