### ISSUE TITLE
Suggest not even mentioning the non-alias commands

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/git-course#11]
Just looking at intro slides. Things like

git commit -a -m "Added .gitignore"  

look a bit scary. I would just go with

git com "Added .gitignore."

(rather than both options) as everyone will have the aliases. Just emphasise early on that these are aliases and you sometimes (when searching on internate) may need to know what they mean, but that's why we have them on the readme page!

I've never used the top one - no point once we have your alias!

**Comment by cgrandin** [comment]
Yeah, I just wanted something that people could refer back to later and understand it if they didn't have the aliases. Maybe we could just have a slide at the end showing the aliases vs. the real command as a reference.

**Comment by andrew-edwards** [comment]
The aliases are listed on the readme.md (which I will tidy up), which is a handy place to look them up. Maybe just define them the first time they're mentioned.

**Comment by cgrandin** [comment]
Yep, still have to get to that but it's nicer if we can just use aliases

**Comment by cgrandin** [comment]
Done - 11fa7a01fc8a2d76dcaa7b78355cd3a121692dc2
