### ISSUE TITLE
'Credentials' slide

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/git-course#12]
In git-course-intro it says that you need to do the credential stuff for each repo. I don't think that's true - I don't seem to have to...

**Comment by andrew-edwards** [comment]
Hmmm.... or maybe I have but have just forgotten. Hmm..

**Comment by cgrandin** [comment]
I think you're right. It puts an entry into .gitconfig that should work local-wide. Let's leave this open so I won't forget!

**Comment by cgrandin** [comment]
Fixed in commit 6d363ddff3140fbb9463f57a2bdb13809af05d5f
