### ISSUE TITLE
Need to add some exercise slides on merge conflicts

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/git-course#15]
This will follow the slides on merge conflicts in the intro slides, we could wither use the same help-friends text file or a new one. I'll assign myself, but let me know what your thoughts are.

**Comment by andrew-edwards** [comment]
Yes, keep going with the same help-friends stuff as everyone will have that set up. It's good not to start new repos too often as that makes it all seem like a lot of work, when in reality that's only a very small part of using GitHub.

So we should run an example (can just do it with the git-course repo) to show how to fix it. Then give an exercise where, in the groups of 4, person 1 and person 2 edit the same lines, and person 3 and person 4 edit the same lines.

We can always do such exercises twice to make sure people really get the hang of it. 

btw I've never used the mergetool thing, so will likely just do it in emacs ;)

**Comment by cgrandin** [comment]
That sounds good to me. I agree we don't want to waste too much time setting up new repos for everything.
