### ISSUE TITLE
Markdown viewer

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/git-course#18]
Andy to try Chrome one from Chris

https://chrome.google.com/webstore/detail/markdown-viewer/ckkdlimhmcjmikdlpkmbgfkaikojcbjk?hl=en

and add notes to git-course-setup. I'll prob keep using Markdown Pad anyway (as I usually have so much open in Chrome).

**Comment by cgrandin** [comment]
Change slide to remove "repository" stuff and have 2 bullets for MD pad and Chrome
