### ISSUE TITLE
Maybe set up a second repo with some code for which people can really mess around with.

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/git-course#2]
It might be nice to keep the git-course repo fairly clean (so it doesn't end up like the git-workshop one), and have a second repo with some R code that people can edit as they like. For that one we don't care if the Network Graph ends up as a mess.
That will also show people how to easily switch between repos.

**Comment by cgrandin** [comment]
Yes, I was planning on having people make their on repo, clone it, add to it, commit, push and add remotes with others so they can immediately collaborate

**Comment by andrew-edwards** [comment]
Okay, so they start from scratch. Nice. I was thinking we split them into groups of 4 or so (not sitting together) and get one person to create a public repo. They could follow us doing a demo of a new repo on the screens. 

We could have a piece of generic code that we share, and they use that (maybe jsut copy and paste from our repo) to create the new repo. Then they can try with a true piece of code they want to share, so we could maybe tell people to bring something (especially Carrie et al. as they want to share stuff).

**Comment by cgrandin** [comment]
That's about what I was thinking. Sub-groups to get the workflow going and appreciated as soon as possible.

**Comment by andrew-edwards** [comment]
We agreed that the first example can just be a text file. No need to get too complicated by looking at R code.

**Comment by andrew-edwards** [comment]
Have started example text to be edited and merged. Now Exercise 2. Realised that Exercise 1 first needs to be people just committing and pushing on their own, not collaborating. Will set that up also - will be best to set up another repo that we don't mind becoming a mess. Keep this one tidy.

**Comment by cgrandin** [comment]
Looks good so far, if you want to close this go ahead but I'll leave it in case you have more to say

**Comment by andrew-edwards** [comment]
Yes, will close as we're not really setting up a second code repo, more supplying files that people can use to start a repo and share with a smaller group.
