### ISSUE TITLE
Make mini-arrowtooth doc with knitr

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/git-course#21]
Use the resDoc style file

**Comment by cgrandin** [comment]
I am thinking that I should just run the code from the csas-latex repo to show this. I don't really want to duplicate code from one repo to another..

**Comment by andrew-edwards** [comment]
Depends if you just want to show it, or get people to run something themselves.

The csas-latex needs tidying up (and should end up with just the MWE), but we can't do that until we've got stuff through CSAS. 

Maybe extend the hake example that people can play with, and then do this one (and maybe full hake) as show-and-tells. And then people can collaborate on their own code in groups (if they want).

**Comment by cgrandin** [comment]
If there's time I will show the ARF doc building steps separately.
