### ISSUE TITLE
Test re-running of hake assessment - remove knitr-catch etc.

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/git-course#25]

**Comment by cgrandin** [comment]
Hake assessment - everything is working including build() and making the assessment on commit cgrandin/hake-assessment@24e43e683a6126f10b1bcd59af213d24c96ddd1e in the hake repo.

**Comment by andrew-edwards** [comment]
Great. Aha - on GitHub that commit HASH doesn't show up as a link, presumably because it's a different repo. Makes sense - it can't cross-reference everything.

**Comment by cgrandin** [comment]
Learned a new thing.. to cross-reference a different repo is username/reponame@commithash, just refresh to see it. Look here, you can reference issues too:
https://stackoverflow.com/questions/8376475/cross-referencing-commits-in-github
