### ISSUE TITLE
Readme file now has somewhat duplicated instructions

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/git-course#3]
So we hadn't been merging (tsk tsk!) and both had put similar things in the readme file. I've fixed the conflict and left my instructions in followed by yours. Mine were essentially taken from your older course and simplified down and they worked for Carrie last year. I don't think we need to give too many commands - I listed just the simple ones that I always use (using your aliases). 
We do need your bit about Macs though.
Prob best to chat before doing further...

**Comment by andrew-edwards** [comment]
I'm not even sure if you really need to make slides for the instructions at the start. Could we just go through the readme file on the screen, having made sure they've done a certain number of steps (GitHub account, download certain stuff etc. ) before coming to the workshop? 
Just maybe no need to duplicate stuff in the talk and the readme. I'm not sure though.....

**Comment by cgrandin** [comment]
Yeah, that will work. I had left it very rough at this point as I have to review POP.

**Comment by cgrandin** [comment]
I just looked at it, it is too long and yes much is duplicated. We can get back to it later, make it more concise and such. I was going for just the basics on there.

**Comment by cgrandin** [comment]
I made a new PDF which has the instructions in a nice slide-by-slide way, and addresses MAC more closely. We agreed to leave the instructions on the README as well.

**Comment by andrew-edwards** [comment]
I'll make a start at tidying up. Some bits will have to be updated to agree with the presentations, but should not be too hard.

**Comment by andrew-edwards** [comment]
I will do this on Tuesday as we have to send out the git-setup pretty soon and this should be somewhat consistent.
Maybe the one-time setup stuff isn't needed on the readme.md, we can just keep the summary of workflow and the aliases as a handy reference. The setup .pdf just won't be easily available to others, but that's okay. We will email it for the course anyway.

**Comment by andrew-edwards** [comment]
Tidied up. Am just adding instructions on generating git-course-setup.pdf without knowing any git stuff.

**Comment by andrew-edwards** [comment]
Not bothering with that final suggestion, since they'd need the .sty file in the right place also. Can maybe add during the course. 
As I was typing the above comment I knew it was bad practice to comment on something you are about to do.... Bound to not work.
