### ISSUE TITLE
Opening non-technical talk for motivation?

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/git-course#4]
I can do this. I'm thinking of some examples from recent projects. In particular when things get held up because it relies on the lead author, who can often get busy with other projects. I have one where that person is me, and others said they had a bit of a time and so asked what could they do, but they had to wait until I got bits and pieces (scatterred Word files) together before they could do anything.

**Comment by cgrandin** [comment]
Ok, sounds good. I've started the git slides, and we can modify to flow after yours. Are you going to use beamer with screenshot pngs?

**Comment by andrew-edwards** [comment]
Probably - I can just take yours as a template.

**Comment by andrew-edwards** [comment]
Another example - email I got on 16/05/17 referred directly to my GitHub size spectra code. I could answer it very quickly because it was all online. Include that in my talk.

**Comment by andrew-edwards** [comment]
Done; yes, included screenshot .png's. Included hake as an example (but pointed out it was hard!).
