### ISSUE TITLE
Test what Notepad does when the file on the disk has changed (emacs asks the user).

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/git-course#5]

**Comment by andrew-edwards** [comment]
We tested (I opened a .tex file in Notepad, Chris changed it and pushed, I fetchec and merged), and Notepad
i) doesn't lock the file;
ii) lets you edit it;
iii) lets you save it without any warning (thereby overwriting the new version that I fetched from Chris.
That is not good. Conclusion: avoid Notepad.

Need to get someone to test RStudio also. Nick K might know (though I think he only uses git for himself and not GitHub).

**Comment by andrew-edwards** [comment]
Over lunch Eric Pederson (from Newfoundland) and Davon Callendar said that Notepad ++ works okay. 
And that RStudio works fine as well.

**Comment by cgrandin** [comment]
Andy will create a slide on the editors

**Comment by cgrandin** [comment]
I installed Notepad++ and it warns you as soon as the file has changed on disk, so it works fine.

**Comment by andrew-edwards** [comment]
Okay, great. I'm checking with people but haven't got an answer yet. Do you want to add a slide saying if people usually just use Notepad for editing simple text files then they need Notepad II and to install it. And that if they use Emacs, vim, or RStudio (for R) then they're fine.

**Comment by andrew-edwards** [comment]
Chris did, and Andy added a bit more in 7c59ea0.

**Comment by andrew-edwards** [comment]
When doing the above comment, realised that you need seven digits from a HASH for GitHub to automatically create a link, so have updated HASH slide with that.
